from wh_script.Pengajaran_dosen_perTa_script import PengajaranDosenPerTA
from wh_script.generate_tempfile_path import FileTemporaryHandler
from wh_script.Pendaftaran_mhs_perTa_script import PendaftaranMhsPerTA
from wh_script.progress_info import use_progress_tracker